source 'https://github.com/CocoaPods/Specs.git'

target 'podTestLibrary', :exclusive => true do
  pod "podTestLibrary", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "podTestLibrary", :path => "../"

  pod 'FBSnapshotTestCase'
end
